### PR TITLE
Feature: Support regular expressions in input.

### PR DESCRIPTION
**Pull request by danielhollas**
This PR adds support for regular expressions in the input instead of just using a simple word.

We also support capturing variables i.e one can generate the URL dynamically based on what was matched.

Example input:
/JIRA-([0-9]+)/https://example.jira.com/$1

So "JIRA-654" will link to https://example.jira.com/654

Note that we do no use a comma as a separator
cause we couldn't use things like /a{1,3}/

One open question: Should we allow arbitrary regexes or perhaps disallow greedy operators like + or * which could be problematic if admin makes a mistake.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Overall this looks fine to me, I think greedy matching is fine, I am happy you added some error handling. 

I would like to keep the syntax consistent though: 

```
/test(.*)/i,https://test.com/$1
```
The split rule can be quite simple, you split on the last index of `,` 

Another thing that should be raised on meta is that we need some way of adding help text here to teach people about the settings, otherwise this is totally ninja hidden forever. Can you raise that on meta, with a quick mockup?

**Comment by danielhollas** [comment]
@SamSaffron thanks! I will change the syntax although in your example you used the "i" qualifiers. Do we want to support this? It seems easier to have it as default ("g qualifier must be by default anyway")

> adding help text here to teach people about the settings, otherwise this is totally ninja hidden forever. Can you raise that on meta, with a quick mockup?

I am not sure I understand you. This feature definitely needs to be documented in the OP on meta, which is the reference. Or did you have something else in mind?

**Comment by danielhollas** [comment]
@SamSaffron I changed the syntax, but see my questions above...

**Comment by danielhollas** [comment]
Thanks @SamSaffron. Support for "i" modifier implemented and I added a comment on meta.

**Comment by SamSaffron** [comment]
Thanks heaps @danielhollas merged it in!

**Pull request merged**
