### PR TITLE
Update initialize-discourse-linkify.js.es6

### PR DESCRIPTION
**Pull request by theloginerror**
Small addition to display the target link on hover

### CODE REVIEW

**Comment by SamSaffron** [comment]
something does not feel right about showing urls as titles, maybe we extend the syntax to allow for a custom title per link?

**Comment by theloginerror** [comment]
I agree, that would be the most graceful solution.

**Comment by danielhollas** [comment]
@theloginerror what is the use case here? Why should auto-linked links behave differently from normal links, given the fact the browsers display links in bottom left corner anyway?

**Comment by ZogStriP** [comment]
I'm gonna close this one as I'm not sure what's the proper use case here. @theloginerror feel free to reply and we might re-open the PR.

**Pull request closed without merging**
