### PR TITLE
FIX: invalid regex would cause an error

### PR DESCRIPTION
**Pull request by fzngagan**

### CODE REVIEW

**Comment by eviltrout** [comment]
Can you explain why this would cause an error? The variable seems to be in the same scope as the other one.

**Comment by fzngagan** [comment]
> Can you explain why this would cause an error? The variable seems to be in the same scope as the other one.

I don't think it is.

**Comment by eviltrout** [comment]
`regex` is declared here, clearly in scope of the function. What am I missing?

https://github.com/discourse/discourse-linkify-words/blob/master/javascripts/discourse-linkify/lib/utilities.js.es6#L35

**Comment by fzngagan** [comment]
> `regex` is declared here, clearly in scope of the function. What am I missing?
> 
> https://github.com/discourse/discourse-linkify-words/blob/master/javascripts/discourse-linkify/lib/utilities.js.es6#L35

I meant that if the regular expression is invalid, it tries to print the variable `word` which is non-existent. It should be `wordOrRegex`.

**Comment by eviltrout** [comment]
Thanks, I see it now!

**Comment by danielhollas** [comment]
@fzngagan thanks for fixing this! I was refactoring the code and changing the variable names and this one slipped through the cracks. :-)

**Pull request merged**
