### PR TITLE
Refactor - 2nd take

### PR DESCRIPTION
**Pull request by danielhollas**
This PR fixes the original #7. In the end the solution to the problem was easy - first get all the matches and then sort them out by the index. You can review this fix separatelly in the third commit.

I've also tried to move some code out of the autolink function so that it's more readable.

After #9 gets merged I'll rebase this. Let me know if I should try to break this down to smaller PRs so that it's more reviewable. Thanks!

### CODE REVIEW

**Comment by SamSaffron** [comment]
maybe we live with #9 for a few days and then merge this in next week ? can you nudge me?

**Comment by danielhollas** [comment]
Yep, thanks!

**Comment by danielhollas** [comment]
Ping @SamSaffron. If you have a bit of time, could you please review and merge this?

Note that there might be an edge condition that is not handled in this PR if a word is matched more than once for some reason. But I think it is rare enough that it can be handled in a subsequent PR.

**Comment by SamSaffron** [comment]
OK lets try it out, it is quite big change very hard for me to reason about all the edge cases, that said as long as you are around to support it I am a-ok!

**Pull request merged**
